2025-07-12 02:02:20 - IncomeService - INFO - ERROR in database operation: (mysql.connector.errors.IntegrityError) 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`telegram_bot`.`income_balance`, CONSTRAINT `fk_income_balance_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`))
[SQL: INSERT INTO income_balance (amount, chat_id, currency, original_amount, income_date, message_id, message, shift_id, trx_id, created_at, updated_at) VALUES (%(amount)s, %(chat_id)s, %(currency)s, %(original_amount)s, %(income_date)s, %(message_id)s, %(message)s, %(shift_id)s, %(trx_id)s, %(created_at)s, %(updated_at)s)]
[parameters: {'amount': 17000.0, 'chat_id': -1002070810630, 'currency': 'KHR', 'original_amount': 17000.0, 'income_date': datetime.datetime(2025, 7, 12, 9, 2, 20, 167262, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>), 'message_id': 7141, 'message': 'KHR 17,000.00 is paid to INFINITE MINI WASH from Chhorn Sopheaktra on 12-Jul-2025 @09:02:15. Transaction Hash is f0f7f9f4.', 'shift_id': False, 'trx_id': None, 'created_at': datetime.datetime(2025, 7, 12, 9, 2, 20, 167692, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>), 'updated_at': datetime.datetime(2025, 7, 12, 9, 2, 20, 167705, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-12 02:02:20 - IncomeService - INFO - ERROR in insert_income: (mysql.connector.errors.IntegrityError) 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`telegram_bot`.`income_balance`, CONSTRAINT `fk_income_balance_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`))
[SQL: INSERT INTO income_balance (amount, chat_id, currency, original_amount, income_date, message_id, message, shift_id, trx_id, created_at, updated_at) VALUES (%(amount)s, %(chat_id)s, %(currency)s, %(original_amount)s, %(income_date)s, %(message_id)s, %(message)s, %(shift_id)s, %(trx_id)s, %(created_at)s, %(updated_at)s)]
[parameters: {'amount': 17000.0, 'chat_id': -1002070810630, 'currency': 'KHR', 'original_amount': 17000.0, 'income_date': datetime.datetime(2025, 7, 12, 9, 2, 20, 167262, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>), 'message_id': 7141, 'message': 'KHR 17,000.00 is paid to INFINITE MINI WASH from Chhorn Sopheaktra on 12-Jul-2025 @09:02:15. Transaction Hash is f0f7f9f4.', 'shift_id': False, 'trx_id': None, 'created_at': datetime.datetime(2025, 7, 12, 9, 2, 20, 167692, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>), 'updated_at': datetime.datetime(2025, 7, 12, 9, 2, 20, 167705, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-12 02:02:20 - TelethonClient - INFO - ERROR saving income: (mysql.connector.errors.IntegrityError) 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`telegram_bot`.`income_balance`, CONSTRAINT `fk_income_balance_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`))
[SQL: INSERT INTO income_balance (amount, chat_id, currency, original_amount, income_date, message_id, message, shift_id, trx_id, created_at, updated_at) VALUES (%(amount)s, %(chat_id)s, %(currency)s, %(original_amount)s, %(income_date)s, %(message_id)s, %(message)s, %(shift_id)s, %(trx_id)s, %(created_at)s, %(updated_at)s)]
[parameters: {'amount': 17000.0, 'chat_id': -1002070810630, 'currency': 'KHR', 'original_amount': 17000.0, 'income_date': datetime.datetime(2025, 7, 12, 9, 2, 20, 167262, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>), 'message_id': 7141, 'message': 'KHR 17,000.00 is paid to INFINITE MINI WASH from Chhorn Sopheaktra on 12-Jul-2025 @09:02:15. Transaction Hash is f0f7f9f4.', 'shift_id': False, 'trx_id': None, 'created_at': datetime.datetime(2025, 7, 12, 9, 2, 20, 167692, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>), 'updated_at': datetime.datetime(2025, 7, 12, 9, 2, 20, 167705, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-12 02:02:20 - TelethonClient - INFO - Traceback: Traceback (most recent call last):
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 772, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`telegram_bot`.`income_balance`, CONSTRAINT `fk_income_balance_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 356, in execute
    self._connection.cmd_query(
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 781, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`telegram_bot`.`income_balance`, CONSTRAINT `fk_income_balance_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/telegram-listener/services/telethon_client_service.py", line 146, in _new_message_listener
    result = await self.service.insert_income(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/models/income_balance_model.py", line 170, in insert_income
    raise e
  File "/root/telegram-listener/models/income_balance_model.py", line 167, in insert_income
    raise e
  File "/root/telegram-listener/models/income_balance_model.py", line 159, in insert_income
    db.commit()
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 356, in execute
    self._connection.cmd_query(
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/telegram-listener/myenv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 781, in cmd_query
    raise get_mysql_exception(
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`telegram_bot`.`income_balance`, CONSTRAINT `fk_income_balance_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`))
[SQL: INSERT INTO income_balance (amount, chat_id, currency, original_amount, income_date, message_id, message, shift_id, trx_id, created_at, updated_at) VALUES (%(amount)s, %(chat_id)s, %(currency)s, %(original_amount)s, %(income_date)s, %(message_id)s, %(message)s, %(shift_id)s, %(trx_id)s, %(created_at)s, %(updated_at)s)]
[parameters: {'amount': 17000.0, 'chat_id': -1002070810630, 'currency': 'KHR', 'original_amount': 17000.0, 'income_date': datetime.datetime(2025, 7, 12, 9, 2, 20, 167262, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>), 'message_id': 7141, 'message': 'KHR 17,000.00 is paid to INFINITE MINI WASH from Chhorn Sopheaktra on 12-Jul-2025 @09:02:15. Transaction Hash is f0f7f9f4.', 'shift_id': False, 'trx_id': None, 'created_at': datetime.datetime(2025, 7, 12, 9, 2, 20, 167692, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>), 'updated_at': datetime.datetime(2025, 7, 12, 9, 2, 20, 167705, tzinfo=<DstTzInfo 'Asia/Phnom_Penh' +07+7:00:00 STD>)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)